create table data_base (id int4 generated by default as identity,
 data_base_name varchar(255), primary key (id));

create table developer (id int4 generated by default as identity,
 mail varchar(255), name varchar(255), telegram varchar(255), tell varchar(255), primary key (id));

create table kazpost_service (id int4 generated by default as identity,
 description varchar(255), documentation boolean not null, naboyu boolean not null, our_prod_address varchar(255),
  our_test_address varchar(255), service_name varchar(255), type_integration varchar(255), data_base_id int4,
   developer_id int4, manager_id int4, postavwik_id int4, primary key (id));

create table manager (id int4 generated by default as identity,
 mail varchar(255), name varchar(255), telegram varchar(255), tell varchar(255), primary key (id));

create table packet (id int4 generated by default as identity,
 packet_name varchar(255), data_base_id int4, primary key (id));

create table postavwik (id int4 generated by default as identity,
 fio varchar(255), mail varchar(255), postavwik_prod_address varchar(255), postavwik_test_address varchar(255),
  prod varchar(255), telegram varchar(255), tell varchar(255), primary key (id));

create table procedura (id int4 generated by default as identity,
 procedura_name varchar(255), packet_id int4, primary key (id));

create table user_name (id int4 generated by default as identity,
 user_name varchar(255), procedura_id int4, primary key (id));

alter table if exists kazpost_service add constraint FKd9dltgdotvpbcnt98ii5a3pri foreign key (data_base_id) references data_base;

alter table if exists kazpost_service add constraint FKiwclio4u2g4xib3l42tdihcoq foreign key (developer_id) references developer;

alter table if exists kazpost_service add constraint FK8usr6mxluwfij2v2oavswornp foreign key (manager_id) references manager;

alter table if exists kazpost_service add constraint FKevvxoq1oxsx5ld0rbkuyyq4r5 foreign key (postavwik_id) references postavwik;

alter table if exists packet add constraint FKm3o7fy4a6fjkrgd7gpxto5tp6 foreign key (data_base_id) references data_base;

alter table if exists procedura add constraint FKeb62fdef07akrmsa5p3ly15xg foreign key (packet_id) references packet;

alter table if exists user_name add constraint FK66ftg3egvpgan871nega75gwj foreign key (procedura_id) references procedura;
