create table data_base (id int4 generated by default as identity,
                        data_base_name varchar(255),
                         primary key (id));

create table developer (id int4 generated by default as identity,
                        mail varchar(255),
                         name varchar(255),
                          telegram varchar(255),
                         tell varchar(255),
                         primary key (id));

create table kazpost_service (id int4 generated by default as identity,
                              description varchar(255),
                               documentation boolean not null,
                              naboyu boolean not null
                             , our_prod_address varchar(255),
                              our_test_address varchar(255),
                               service_name varchar(255),
                               type_integration varchar(255),
                                data_base_id int4,
                              developer_id int4, manager_id int4,
                               postavwik_id int4, primary key (id));

create table manager (id int4 generated by default as identity,
                      mail varchar(255),
                       name varchar(255),
                        telegram varchar(255),
                       tell varchar(255),
                        primary key (id));

create table packet (id int4 generated by default as identity,
                     packet_name varchar(255),
                      data_base_id int4,
                       primary key (id));

create table postavwik (id int4 generated by default as identity,
                        fio varchar(255),
                         mail varchar(255),
                          postavwik_prod_address varchar(255),
                           postavwik_test_address varchar(255),
                        prod varchar(255),
                         telegram varchar(255),
                          tell varchar(255),
                           primary key (id));

create table procedura (id int4 generated by default as identity,
                        procedura_name varchar(255),
                         packet_id int4, primary key (id));

create table user_name (id int4 generated by default as identity,
                        user_name varchar(255),
                         procedura_id int4, primary key (id));

alter table if exists kazpost_service add constraint FK_data_base_id foreign key (data_base_id) references data_base;

alter table if exists kazpost_service add constraint FK_developer_id foreign key (developer_id) references developer;

alter table if exists kazpost_service add constraint FK_manager_id foreign key (manager_id) references manager;

alter table if exists kazpost_service add constraint FK_postavwik_id foreign key (postavwik_id) references postavwik;

alter table if exists packet add constraint FK_data_base_id foreign key (data_base_id) references data_base;

alter table if exists procedura add constraint FK_packet_id foreign key (packet_id) references packet;

alter table if exists user_name add constraint FK_procedura_id foreign key (procedura_id) references procedura;

insert into kazpost_service (description, documentation, naboyu, our_prod_address, our_test_address, service_name, type_integration, data_base_id, developer_id, manager_id, postavwik_id)
VALUES ('tsets', true, true, '34sdfsdf', 'rsers', 'serfsef', 'tserfs', 1, 1,1, 1);
insert into data_base (data_base_name) values ('d-1');
insert into developer (mail, name, telegram, tell)  values ('m-1', 'name-1', 't-1', '71345345134');
insert into manager (mail, name, telegram, tell) values ('m-1', 'mname-1', 't-1', '123523424');
insert into postavwik (fio, mail, postavwik_prod_address, postavwik_test_address, prod, telegram, tell)
VALUES ('fio', 'mail', 'pos-prod-add','pos-test-add', 'prod', 't-1', '6134535435354');
insert into packet (packet_name, data_base_id) VALUES ('test-1', 1);
insert into procedura (procedura_name, packet_id) VALUES ('pr-name', 1);
insert into user_name (user_name, procedura_id) VALUES ('usr', 2);
select * from kazpost_service;
select * from data_base;
select * from developer;
select * from manager;
select * from postavwik;
select * from procedura;
select * from user_name;
select * from packet;